version: "3.3"

services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3309:3306"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql

  flask:
    depends_on:
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "/media/jeferson/hd_jeferson/curso_docker/5_compose/6_bind_mount_compose/flask:/appclear"
    networks:
      - dockercompose

networks:
  dockercompose:
